--//------------------------------------------------------------------------//---
-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756             --
-- Author: Krystsina Bahdanava                                                --
--   at:        2018-10-22 23:56:45 MSK                                       --
--   site:      Oracle Database 11g                                           --
--   type:      Oracle Database 11g                                           --
--//------------------------------------------------------------------------//---


CREATE TABLE att_address (
    be_id        NUMBER NOT NULL,
    be_name      VARCHAR2(200) NOT NULL
   ,
    address      VARCHAR2(200) 
   ,
    region_oid   NUMBER NOT NULL,
    is_active    NUMBER,
    start_date   DATE,
    end_date     DATE
);

ALTER TABLE att_address ADD CONSTRAINT address_pk PRIMARY KEY ( be_id );

ALTER TABLE att_address MODIFY (IS_ACTIVE DEFAULT 1);
ALTER TABLE att_address MODIFY (START_DATE DEFAULT '01-DEC-1900');
ALTER TABLE att_address MODIFY (END_DATE DEFAULT '31-DEC-9999');

CREATE TABLE att_cart (
    be_id          NUMBER NOT NULL,
    be_name        VARCHAR2(200)
   ,
    cart_code      VARCHAR2(200)
   ,
    is_active      NUMBER,
    start_date     DATE,
    end_date       DATE,
    menu_pos_oid   NUMBER NOT NULL
);

ALTER TABLE att_cart MODIFY (IS_ACTIVE DEFAULT 1);
ALTER TABLE att_cart MODIFY (START_DATE DEFAULT '01-DEC-1900');
ALTER TABLE att_cart MODIFY (END_DATE DEFAULT '31-DEC-9999');

ALTER TABLE att_cart ADD CONSTRAINT att_cart_pk PRIMARY KEY ( be_id );

CREATE TABLE att_city (
    be_id         NUMBER NOT NULL,
    be_name       VARCHAR2(200)
   ,
    city_name     VARCHAR2(200)
   ,
    is_active     NUMBER,
    start_date    DATE,
    end_date      DATE,
    country_oid   NUMBER NOT NULL
);

ALTER TABLE att_city ADD CONSTRAINT city_pk PRIMARY KEY ( be_id );

ALTER TABLE att_city MODIFY (IS_ACTIVE DEFAULT 1);
ALTER TABLE att_city MODIFY (START_DATE DEFAULT '01-DEC-1900');
ALTER TABLE att_city MODIFY (END_DATE DEFAULT '31-DEC-9999');

CREATE TABLE att_country (
    be_id               NUMBER NOT NULL,
    be_name             VARCHAR2(200),
    country_full_name   VARCHAR2(200),
    country_code        VARCHAR2(200),
    is_active           NUMBER,
    start_date          DATE,
    end_date            DATE
);

ALTER TABLE att_country ADD CONSTRAINT country_pk PRIMARY KEY ( be_id );

ALTER TABLE att_country MODIFY (IS_ACTIVE DEFAULT 1);
ALTER TABLE att_country MODIFY (START_DATE DEFAULT '01-DEC-1900');
ALTER TABLE att_country MODIFY (END_DATE DEFAULT '31-DEC-9999');

CREATE TABLE att_feedback (
    be_id        NUMBER NOT NULL,
    be_name      VARCHAR2(200),
    mark         NUMBER,
    "COMMENT"    VARCHAR2(200),
    user_oid     NUMBER NOT NULL,
    rstrnt_oid   NUMBER NOT NULL,
    is_active    NUMBER,
    start_date   DATE,
    end_date     DATE
);

ALTER TABLE att_feedback ADD CONSTRAINT att_mark_pk PRIMARY KEY ( be_id );
ALTER TABLE att_feedback MODIFY (START_DATE DEFAULT '01-DEC-1900');
ALTER TABLE att_feedback MODIFY (END_DATE DEFAULT '31-DEC-9999');

CREATE TABLE att_menu (
    be_id        NUMBER NOT NULL,
    be_name      VARCHAR2(200),
    dish_name    VARCHAR2 (200),
    dish_desc    VARCHAR2 (200),
    price        NUMBER,
    dish_pic     BLOB,
    rstrnt_oid   NUMBER NOT NULL,
    is_active    NUMBER,
    start_date   DATE,
    end_date     DATE
);

ALTER TABLE att_menu ADD CONSTRAINT att_menu_pk PRIMARY KEY ( be_id );

CREATE TABLE att_order (
    be_id         NUMBER NOT NULL,
    be_name       VARCHAR2 (200)
   ,
    is_active     NUMBER,
    start_date    DATE,
    end_date      DATE,
    address_oid   NUMBER NOT NULL,
    client_oid    NUMBER NOT NULL,
    status_oid    NUMBER NOT NULL,
    cart_oid      NUMBER NOT NULL
);

ALTER TABLE att_order ADD CONSTRAINT att_order_pk PRIMARY KEY ( be_id );

CREATE TABLE att_order_status (
    be_id        NUMBER NOT NULL,
    be_name      VARCHAR2 (200)
   ,
    is_active    NUMBER,
    start_date   DATE,
    end_date     DATE,
    status       VARCHAR2 (200)
);

ALTER TABLE att_order_status ADD CONSTRAINT att_order_status_pk PRIMARY KEY ( be_id );

CREATE TABLE att_region (
    be_id         NUMBER NOT NULL,
    be_name       VARCHAR2 (200)
   ,
    is_active     NUMBER,
    start_date    DATE,
    end_date      DATE
   ,
    city_oid      NUMBER NOT NULL
);

ALTER TABLE att_region ADD CONSTRAINT att_region_pk PRIMARY KEY ( be_id );

CREATE TABLE att_rest_category (
    be_id           NUMBER NOT NULL,
    be_name         VARCHAR2 (200)
   ,
    category_name   VARCHAR2 (200)
   ,
    is_active       NUMBER,
    start_date      DATE,
    end_date        DATE
);

ALTER TABLE att_rest_category ADD CONSTRAINT att_rest_category_pk PRIMARY KEY ( be_id );

CREATE TABLE att_role (
    be_id        NUMBER NOT NULL,
    be_name      VARCHAR2 (200)
   ,
    role_name    VARCHAR2 (200)
   ,
    is_active    NUMBER,
    start_date   DATE,
    end_date     DATE
);

ALTER TABLE att_role MODIFY (IS_ACTIVE DEFAULT 1);
ALTER TABLE att_role MODIFY (START_DATE DEFAULT '01-DEC-1900');
ALTER TABLE att_role MODIFY (END_DATE DEFAULT '31-DEC-9999');

ALTER TABLE att_role ADD CONSTRAINT att_role_pk PRIMARY KEY ( be_id );

CREATE TABLE att_rstrnt (
    be_id          NUMBER NOT NULL,
    be_name        VARCHAR2(200),
    rstrnt_name    VARCHAR2(200),
    is_active      NUMBER,
    start_date     DATE,
    end_date       DATE,
    category_oid   NUMBER NOT NULL
);

ALTER TABLE att_rstrnt ADD CONSTRAINT att_rstrnt_pk PRIMARY KEY ( be_id );
ALTER TABLE att_rstrnt ADD LOGO varchar2(255);
ALTER TABLE att_rstrnt ADD SCHEDULE varchar2(20);

ALTER TABLE att_rstrnt MODIFY (IS_ACTIVE DEFAULT 1);
ALTER TABLE att_rstrnt MODIFY (START_DATE DEFAULT '01-DEC-1900');
ALTER TABLE att_rstrnt MODIFY (END_DATE DEFAULT '31-DEC-9999');
ALTER TABLE att_rstrnt MODIFY (LOGO varchar2(255));

CREATE TABLE att_unauthorised_client (
    be_id        NUMBER NOT NULL,
    be_name      VARCHAR2(200)
   ,
    name         VARCHAR2(200)
   ,
    phone        VARCHAR2(200)
   ,
    is_active    NUMBER,
    start_date   DATE,
    end_date     DATE
);

ALTER TABLE att_unauthorised_client ADD CONSTRAINT att_client_pk PRIMARY KEY ( be_id );

CREATE TABLE att_user (
    be_id        NUMBER NOT NULL,
    be_name      VARCHAR2(200)
   ,
    user_name    VARCHAR2(200)
   ,
    password     VARCHAR2(200)
   ,
    role_oid     NUMBER NOT NULL,
    is_active    NUMBER,
    start_date   DATE,
    end_date     DATE
);

ALTER TABLE ATT_USER ADD NAME VARCHAR2(200);
ALTER TABLE ATT_USER ADD SURNAME VARCHAR2(200);

ALTER TABLE ATT_USER MODIFY (ROLE_OID DEFAULT 1);
ALTER TABLE ATT_USER MODIFY (IS_ACTIVE DEFAULT 1);
ALTER TABLE ATT_USER MODIFY (START_DATE DEFAULT '01-DEC-1900');
ALTER TABLE ATT_USER MODIFY (END_DATE DEFAULT '31-DEC-9999');

ALTER TABLE att_user ADD CONSTRAINT att_user_pk PRIMARY KEY ( be_id );

ALTER TABLE att_address
    ADD CONSTRAINT att_address_att_region_fk FOREIGN KEY ( region_oid )
        REFERENCES att_region ( be_id );

ALTER TABLE att_cart
    ADD CONSTRAINT att_cart_att_menu_fk FOREIGN KEY ( menu_pos_oid )
        REFERENCES att_menu ( be_id );

ALTER TABLE att_feedback
    ADD CONSTRAINT att_feedback_att_rstrnt_fk FOREIGN KEY ( rstrnt_oid )
        REFERENCES att_rstrnt ( be_id );

ALTER TABLE att_feedback
    ADD CONSTRAINT att_feedback_att_user_fk FOREIGN KEY ( user_oid )
        REFERENCES att_user ( be_id );

ALTER TABLE att_menu
    ADD CONSTRAINT att_menu_att_rstrnt_fk FOREIGN KEY ( rstrnt_oid )
        REFERENCES att_rstrnt ( be_id );

ALTER TABLE att_order
    ADD CONSTRAINT att_order_address_fk FOREIGN KEY ( address_oid )
        REFERENCES att_address ( be_id );

ALTER TABLE att_order
    ADD CONSTRAINT att_order_att_cart_fk FOREIGN KEY ( cart_oid )
        REFERENCES att_cart ( be_id );

ALTER TABLE att_order
    ADD CONSTRAINT att_order_att_client_fk FOREIGN KEY ( client_oid )
        REFERENCES att_unauthorised_client ( be_id );

ALTER TABLE att_order
    ADD CONSTRAINT att_order_att_order_status_fk FOREIGN KEY ( status_oid )
        REFERENCES att_order_status ( be_id );

ALTER TABLE att_region
    ADD CONSTRAINT att_region_att_city_fk FOREIGN KEY ( city_oid )
        REFERENCES att_city ( be_id );

ALTER TABLE att_rstrnt
    ADD CONSTRAINT att_rst_att_rest_cat_fk FOREIGN KEY ( category_oid )
        REFERENCES att_rest_category ( be_id );

ALTER TABLE att_user
    ADD CONSTRAINT att_user_att_role_fk FOREIGN KEY ( role_oid )
        REFERENCES att_role ( be_id );

ALTER TABLE att_city
    ADD CONSTRAINT city_country_fk FOREIGN KEY ( country_oid )
        REFERENCES att_country ( be_id );



